language: java
install: true
jdk:
  - openjdk10
branches:
  only:
    - development
    - release
notifications:
  email:
    recipients:
      - 209418@edu.p.lodz.pl
      - 209377@edu.p.lodz.pl
      - 209364@edu.p.lodz.pl
      - 209279@edu.p.lodz.pl
      - 209472@edu.p.lodz.pl
    on_success: never
    on_failure: always
jobs:
  include:
    - stage: compile
      name: "Compiling"
      script: - mvn install -DskipTests
    - stage: test
      name: "Testing"
      script: - mvn verify
    - stage: deploy
      name: deploy
      if: branch = release
before_deploy:
  - git config --local user.name "kostdmex"
  - git config --local user.email "209418@edu.p.lodz.pl"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: /home/travis/build/IIS-ZPI/ZPI_2019_Dzienni_IO1_Grupa2/target/ZPI_2019_Dzienni_IO1_Grupa2-1.0-SNAPSHOT.jar
  skip_cleanup: true
  on:
    branch: release
