language: java
install: true
jdk:
- openjdk10
branches:
  only:
    - development
script:
- mvn install
jobs:
  include:
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      before_deploy:
        - git config --local user.name "YOUR GIT USER NAME"
        - git config --local user.email "YOUR GIT USER EMAIL"
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
        deploy:
          provider: releases
          api_key:
            secure: GITHUB_TOKEN
          file: travis-docker-demo-$TARGET-$TRAVIS_BUILD_NUMBER.tar.gz
          skip_cleanup: true
          on:
            branch: release